apiVersion: v1
kind: Service
metadata:
  labels:
    app: shiori
  name: shiori
  namespace: shiori
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app: shiori
  type: NodePort

