apiVersion: packages.glasskube.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: my-quickwit
  namespace: ns-1
spec:
  packageInfo:
    name: quickwit
    repositoryName: glasskube
    version: v0.8.1+5
  values:
    defaultIndexRootUri:
      value: asdf
    metastoreUri:
      value: asdf
    quickwitDomain:
      value: ""
    s3AccessKeyId:
      value: ""
    s3Endpoint:
      value: ""
    s3Flavor:
      value: ""
    s3Region:
      value: ""
    s3SecretAccessKey:
      value: ""
